for ws_id in $workspace_ids; do
  echo "Assigning team write access to workspace ID: $ws_id"

  access_response=$(curl -s -w "\n%{http_code}" --request POST \
    --url "https://app.terraform.io/api/v2/team-workspaces" \
    --header "Authorization: Bearer $TFC_TOKEN" \
    --header "Content-Type: application/vnd.api+json" \
    --data "{
      \"data\": {
        \"type\": \"team-workspaces\",
        \"attributes\": {
          \"access\": \"write\"
        },
        \"relationships\": {
          \"team\": {
            \"data\": {
              \"id\": \"$team_id\",
              \"type\": \"teams\"
            }
          },
          \"workspace\": {
            \"data\": {
              \"id\": \"$ws_id\",
              \"type\": \"workspaces\"
            }
          }
        }
      }
    }")

  http_code=$(echo "$access_response" | tail -n1)
  response_body=$(echo "$access_response" | sed '$d')

  if [[ "$http_code" -ne 201 ]]; then
    echo "❌ Failed to assign access to $ws_id. Response:"
    echo "$response_body"
  else
    echo "✅ Write access granted to workspace $ws_id"
  fi
done
