Run PROJECT_NAME="oci-${SYSTEM}-${APP}"
Using Project Name: oci-test-demo
Checking if project already exists...
Creating project: oci-test-demo
Project created with ID: prj-hqrhygPhk4A9tJ2a
Creating workspace: oci-test-demo-dev-001
Workspace created: oci-test-demo-dev-001 (ID: ws-QUNirZRK8w9wWoc1)
Creating workspace: oci-test-demo-qa-001
Workspace created: oci-test-demo-qa-001 (ID: ws-TpCptvDR4X1ruLa9)
Creating team: team-demo-test
Team creation response:
{
  "data": {
    "id": "team-CMP2PntzyKa2yEoi",
    "type": "teams",
    "attributes": {
      "name": "team-demo-test",
      "users-count": 0,
      "sso-team-id": null,
      "visibility": "organization",
      "allow-member-token-management": true,
      "permissions": {
        "can-update-membership": true,
        "can-destroy": true,
        "can-update-organization-access": true,
        "can-update-api-token": true,
        "can-update-visibility": true,
        "can-update-name": true,
        "can-update-sso-team-id": true,
        "can-update-member-token-management": true,
        "can-view-api-token": true
      },
      "organization-access": {
        "manage-policies": false,
        "manage-workspaces": false,
        "manage-vcs-settings": false,
        "manage-policy-overrides": false,
        "manage-modules": false,
        "manage-providers": false,
        "manage-run-tasks": false,
        "manage-projects": false,
        "manage-membership": false,
        "manage-teams": false,
        "manage-organization-access": false,
        "access-secret-teams": false,
        "read-projects": false,
        "read-workspaces": false,
        "manage-agent-pools": false,
        "manage-public-providers": false,
        "manage-public-modules": false
      }
    },
    "relationships": {
      "organization": {
        "data": {
          "id": "***",
          "type": "organizations"
        }
      },
      "users": {
        "data": []
      },
      "organization-memberships": {
        "data": []
      },
      "authentication-token": {
        "meta": {}
      },
      "authentication-tokens": {
        "meta": {}
      }
    },
    "links": {
      "self": "/api/v2/teams/team-CMP2PntzyKa2yEoi"
    }
  }
}
Team created with ID: team-CMP2PntzyKa2yEoi
