for ws_id in "${workspace_ids[@]}"; do
  echo "Assigning team write access to workspace ID: $ws_id"

  assign_response=$(curl -s -w "\n%{http_code}" --request POST \
    --url "https://app.terraform.io/api/v2/team-workspaces" \
    --header "Authorization: Bearer $TFC_TOKEN" \
    --header "Content-Type: application/vnd.api+json" \
    --data "{
      \"data\": {
        \"type\": \"team-workspaces\",
        \"attributes\": {
          \"access\": \"write\"
        },
        \"relationships\": {
          \"workspace\": {
            \"data\": {
              \"id\": \"$ws_id\",
              \"type\": \"workspaces\"
            }
          },
          \"team\": {
            \"data\": {
              \"id\": \"$team_id\",
              \"type\": \"teams\"
            }
          }
        }
      }
    }")

  status=$(echo "$assign_response" | tail -n1)
  if [[ "$status" -eq 201 ]]; then
    echo "Team write access assigned to $ws_id"
  else
    echo "Failed to assign team access to $ws_id. Status: $status"
    echo "$assign_response"
  fi
done
