Tf code:

variable "tenancy_ocid" {
  type        = string
  description = "The OCID of the OCI tenancy"
}

variable "user_ocid" {
  type        = string
  description = "The OCID of the OCI user"
}

variable "private_key" {
  type        = string
  description = "The private key for OCI authentication"
}

variable "fingerprint" {
  type        = string
  description = "The fingerprint of the OCI public key"
}

variable "region" {
  type        = string
  description = "The OCI region"
}

provider "oci" {
tenancy_ocid = var.tenancy_ocid
user_ocid = var.user_ocid
private_key = var.private_key
fingerprint = var.fingerprint
region = var.region
}

resource "oci_objectstorage_bucket" "non_compliant" {
  compartment_id = "ocid1.compartment.oc1..aaaaaaaa6epgbx4ujj5fyqokmrstwwm3gizipwfxkkqpc3zpozwgzmf6ddaq"
  name           = "non-compliant-bucket-${random_id.unique.hex}"
  namespace      = "axlo0xjafwdf"
}

# resource "oci_objectstorage_bucket" "compliant" {
#   compartment_id = "ocid1.compartment.oc1..example"
#   name           = "compliant-bucket-${random_id.unique.hex}"
#   namespace      = "your-namespace"
#   kms_key_id     = "ocid1.key.oc1..example"
# }

resource "random_id" "unique" {
  byte_length = 4
}

-----

OPA policy on TFC UI. 

package terraform

# Deny if any bucket lacks kms_key_id
deny[msg] {
    resource := input.plan.resource_changes[_]
    resource.type == "oci_objectstorage_bucket"
    resource.change.actions[_] == "create"
    not resource.change.after.kms_key_id
    msg := sprintf("Bucket '%s' does not have kms_key_id defined", [resource.change.after.name])
}

# Deny if kms_key_id is empty
deny[msg] {
    resource := input.plan.resource_changes[_]
    resource.type == "oci_objectstorage_bucket"
    resource.change.actions[_] == "create"
    resource.change.after.kms_key_id == ""
    msg := sprintf("Bucket '%s' has an empty kms_key_id", [resource.change.after.name])
}

--------

PS C:\Users\ramesh.kotagiri\Desktop\Source\iac-corecloudplatform> cat .\plan.json
{"format_version":"1.2","terraform_version":"1.12.2","variables":{"fingerprint":{"value":"b4:25:bd:14:06:46:58:dc:fe:69:02:8d:ae:03:37:7d"},"private_key":{"value":"-----BEGIN PRIVATE KEY-----MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC5ZaHEHPBIh7fWUvGB32oS0lSd8Ec9uy2fF0zu265JBZezrqOljPCiOA0U08jSBwlwDdwB7eIf3iMR/uBDmdBaOJ9UfAbsDbMRakhmeWbRJhivDYFPTP2e/8I6XaEgNAMe92IcrJ/UEpv5Nrrw3AxArSE/RBkMBXV+PBZg5wc910gPMvU7cu7I8sL8qtcTUD7iFG/tkxgo8cfLmJ4eXGSW9W9yL3AwPRerGXfy6CB88yNhfnUtceS+m57p2c2gbSgtr8sBp4HhlD8Zu7MKtSoVZy4w4F40EPPQ9qR6HKLKQn2haU1v/N7akEfOkqlq2tZ02/vpMffFM1xWPYFkJMwNAgMBAAECggEASch6wrPJpPPuY+uKlec2LdtrNZgEojq2A1Sgl4byK7mAEFB2bFJVChpIintmtr96MBAz+MiVb51WU7kdw4mZc+6I6nSZxKQHGe00dyPlmWMR+8jiJ486eGbNA7FziH9qpo5Ji6Pfz+TAEkSHzYelkK/WRXlyhmg9xElhlpsbNK6lVgc0nsRcwaNlhdA5StCbGWyHqT+IVjlxoN1K50TUQHFBdPTGkpRneJLIStw6a506k5kmQJ+vfp4jiWMScSkRbJztki/NujjUPmUHmyZpkR++uvgScnalhRYIrTx8kVCDfugW6d/gkcGqn/9R9NFmiU4WluMwwqoplU98iQMEuQKBgQDfoYE9gkan89+LClQZmc0rydhrGHkFjwL9BrYm7Yvt67RtLKVNXpytPhBRdMHf0nZjXp/nHHK64ajCw0x/d1n2zmJQokHBEAfqefkT06gS2fTkBH9OzTd4MiRgYODQJ4zHn2vcVDaTX3ZHm2hrVhtEaRF2CyX046yA1hyXh5yJ8wKBgQDUO2VUVbxALXgghAS7rZeq73xCLfoAK7XTe2EfiRNAOK0YRnW+obMBVbZcSJe0JzPhUN0ViblqYp2ah+SkgyTfxZfbFKar+IdXAcgtZXAFWn0lk0YX/p78BoNzybga1Hl9Cee2domr/MwahwvV4a0k1dIuCAna+UpGjNuywQjR/wKBgQDcQ1DuanB5YITfh+7JwGkLJiXZZiNdTDzfR0sGEJbwYmY12fF+wR+Eq0qbUGrcr4kX2s2Ybra6RyVXn9CrA71CkIjZbtdg9w807apc0u4Kk07Xf259CTgHVSvrGcCUhT/uJqGwQ+n1QeNYKEOy5P66ZNpj8BsUl2MDCuDihxmx7QKBgQC5OWFVOkJCzKwzzKSI25cr4zlSVOgEsCFPgjWgnTSE7zH6prvqdRtSRekTH3PvEevQcI+TVZDSDWE5VfKxtZdACSZgWOSh4BTWVcLMA+TBd1kTqzYYiOteT5z4OAwKtneVLkjhUREUXlwPpt8oen5vUIHQFMntJ3awngy8NIarJwKBgEd+qGrLlesvX9oOkFtNeWWabVVYkJ7WSZ776id7bmgEC9iZzNI74+fF5L++ARkuL7pPNL+DIJQ33vICjnum3KWaQe/UZT9AwT5HwDZOTM8Tizlk8R+2DwvtJTbCsBdpnC6VUAcj25Cp1DERGbYVPASsdjVR4WMjdmjdNsuUrBRb-----END PRIVATE KEY-----"},"region":{"value":"us-phoenix-1"},"tenancy_ocid":{"value":"ocid1.tenancy.oc1..aaaaaaaamtvtn7a7y4b7mo7yihimhfbjf5wqhqyzi5t7djdnkoatxyqkq5aa"},"user_ocid":{"value":"ocid1.user.oc1..aaaaaaaacawq3yo4d2qoyn6n4dqbqpmump3htnbr6lomafgueki3ffcuxwyq"}},"planned_values":{"root_module":{"resources":[{"address":"oci_objectstorage_bucket.non_compliant","mode":"managed","type":"oci_objectstorage_bucket","name":"non_compliant","provider_name":"registry.terraform.io/hashicorp/oci","schema_version":0,"values":{"access_type":"NoPublicAccess","compartment_id":"ocid1.compartment.oc1..aaaaaaaa6epgbx4ujj5fyqokmrstwwm3gizipwfxkkqpc3zpozwgzmf6ddaq","metadata":null,"namespace":"axlo0xjafwdf","retention_rules":[],"timeouts":null},"sensitive_values":{"defined_tags":{},"freeform_tags":{},"retention_rules":[]}},{"address":"random_id.unique","mode":"managed","type":"random_id","name":"unique","provider_name":"registry.terraform.io/hashicorp/random","schema_version":0,"values":{"byte_length":4,"keepers":null,"prefix":null},"sensitive_values":{}}]}},"resource_changes":[{"address":"oci_objectstorage_bucket.non_compliant","mode":"managed","type":"oci_objectstorage_bucket","name":"non_compliant","provider_name":"registry.terraform.io/hashicorp/oci","change":{"actions":["create"],"before":null,"after":{"access_type":"NoPublicAccess","compartment_id":"ocid1.compartment.oc1..aaaaaaaa6epgbx4ujj5fyqokmrstwwm3gizipwfxkkqpc3zpozwgzmf6ddaq","metadata":null,"namespace":"axlo0xjafwdf","retention_rules":[],"timeouts":null},"after_unknown":{"approximate_count":true,"approximate_size":true,"auto_tiering":true,"bucket_id":true,"created_by":true,"defined_tags":true,"etag":true,"freeform_tags":true,"id":true,"is_read_only":true,"kms_key_id":true,"name":true,"object_events_enabled":true,"object_lifecycle_policy_etag":true,"replication_enabled":true,"retention_rules":[],"storage_tier":true,"time_created":true,"versioning":true},"before_sensitive":false,"after_sensitive":{"defined_tags":{},"freeform_tags":{},"retention_rules":[]}}},{"address":"random_id.unique","mode":"managed","type":"random_id","name":"unique","provider_name":"registry.terraform.io/hashicorp/random","change":{"actions":["create"],"before":null,"after":{"byte_length":4,"keepers":null,"prefix":null},"after_unknown":{"b64_std":true,"b64_url":true,"dec":true,"hex":true,"id":true},"before_sensitive":false,"after_sensitive":{}}}],"configuration":{"provider_config":{"oci":{"name":"oci","full_name":"registry.terraform.io/hashicorp/oci","expressions":{"fingerprint":{"references":["var.fingerprint"]},"private_key":{"references":["var.private_key"]},"region":{"references":["var.region"]},"tenancy_ocid":{"references":["var.tenancy_ocid"]},"user_ocid":{"references":["var.user_ocid"]}}},"random":{"name":"random","full_name":"registry.terraform.io/hashicorp/random"}},"root_module":{"resources":[{"address":"oci_objectstorage_bucket.non_compliant","mode":"managed","type":"oci_objectstorage_bucket","name":"non_compliant","provider_config_key":"oci","expressions":{"compartment_id":{"constant_value":"ocid1.compartment.oc1..aaaaaaaa6epgbx4ujj5fyqokmrstwwm3gizipwfxkkqpc3zpozwgzmf6ddaq"},"name":{"references":["random_id.unique.hex","random_id.unique"]},"namespace":{"constant_value":"axlo0xjafwdf"}},"schema_version":0},{"address":"random_id.unique","mode":"managed","type":"random_id","name":"unique","provider_config_key":"random","expressions":{"byte_length":{"constant_value":4}},"schema_version":0}],"variables":{"fingerprint":{"description":"The fingerprint of the OCI public key"},"private_key":{"description":"The private key for OCI authentication"},"region":{"description":"The OCI region"},"tenancy_ocid":{"description":"The OCID of the OCI tenancy"},"user_ocid":{"description":"The OCID of the OCI user"}}}},"relevant_attributes":[{"resource":"random_id.unique","attribute":["hex"]}],"timestamp":"2025-06-13T16:35:59Z","applyable":true,"complete":true,"errored":false}
PS C:\Users\ramesh.kotagiri\Desktop\Source\iac-corecloudplatform>

