[
  "failed running OPA policy evaluation run for policy: data.terraform.deny, (output: \"1 error occurred: /home/tfc-agent/.tfc-agent/component/policy/policy-runs/poleval-d2NsQTiNAqhyM8Ye/policy/oci-encryption-policies-opa/require-bucket-encryption-opa.rego:8: rego_type_error: undefined function has_key\\n\") (exit 2)"
]
