PS C:\Users\ramesh.kotagiri\Desktop\Source\iac-corecloudplatform> git push --set-upstream origin feature/bucket-encryption-policy
Enumerating objects: 20, done.
Counting objects: 100% (20/20), done.
Delta compression using up to 4 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (19/19), 60.66 MiB | 3.37 MiB/s, done.
Total 19 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), done.
remote: error: Trace: 51bc9a68efa65ef7f2957480dcb43b19fea0481c22bd67f6ff01596e13d2abca
remote: error: See https://gh.io/lfs for more information.
remote: error: File .terraform/providers/registry.terraform.io/hashicorp/oci/7.5.0/windows_amd64/terraform-provider-oci_v7.5.0 is 219.21 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/Multiplan-Ops/iac-corecloudplatform.git
 ! [remote rejected] feature/bucket-encryption-policy -> feature/bucket-encryption-policy (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/Multiplan-Ops/iac-corecloudplatform.git'
PS C:\Users\ramesh.kotagiri\Desktop\Source\iac-corecloudplatform>
