if [[ -n "$SELECTED_WS" ]]; then
  IFS=',' read -ra WS_NAMES <<< "$SELECTED_WS"
  echo "Deleting selected workspaces: ${WS_NAMES[*]}"

  for name in "${WS_NAMES[@]}"; do
    ws_id=$(curl -s --request GET \
      --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/workspaces" \
      --header "Authorization: Bearer $TFC_TOKEN" \
      --header "Content-Type: application/vnd.api+json" | jq -r \
      --arg pname "$name" '.data[] | select(.attributes.name == $pname) | .id')

    if [[ -n "$ws_id" ]]; then
      echo "Deleting workspace: $name (ID: $ws_id)"
      curl -s --request DELETE \
        --url "https://app.terraform.io/api/v2/workspaces/$ws_id" \
        --header "Authorization: Bearer $TFC_TOKEN" \
        --header "Content-Type: application/vnd.api+json"
    else
      echo "Workspace '$name' not found. Skipping."
    fi
  done
else
  echo "No selected workspaces provided. Deleting all workspaces in project..."
  # existing loop for all project workspaces
fi


selected_workspaces:
  description: 'Comma-separated list of workspace names to delete (optional)'
  required: false
  type: string
