import "tfplan/v2" as tfplan

# Filter all OCI Object Storage buckets from the Terraform plan
all_buckets = filter tfplan.resource_changes as _, rc {
  rc.type is "oci_objectstorage_bucket" and rc.mode is "managed"
}

# Main rule: Ensure every bucket has a kms_key_id
main = rule {
  all all_buckets as _, bucket {
    bucket.change.after.kms_key_id is not null and
    bucket.change.after.kms_key_id != ""
  }
}
