resource "tfe_policy_set" "oci_encryption_policies" {
  name         = "oci-encryption-policies-poc"
  description  = "POC policy set for OCI bucket encryption"
  organization = var.organization
  kind         = "sentinel"
  policy_ids   = [tfe_policy.encryption_policy.id]
}
