 OPA Policy to Deny Manual DB_PASSWORD Variable Definition

 package terraform.security

deny[msg] {
  input.resource_type == "variable"
  input.name == "DB_PASSWORD"
  msg := "Manual setting of DB_PASSWORD is not allowed. Use GitHub Actions only."
}

OPA Policy to Deny Terraform Creating Vault Secrets

package terraform.security

deny[msg] {
  input.resource_type == "oci_vault_secret"
  input.action == "create"
  msg := "Creating Vault secrets from Terraform is not allowed."
}
