name: Test OCI Authentication

on:
  workflow_dispatch: 

jobs:
  verify-oci-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Setup OCI CLI
        uses: oracle-actions/setup-oci-cli@v1
        with:
          version: 3.0.0

      - name: Configure OCI Credentials
        env:
          OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_API_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
        run: |
          mkdir -p ~/.oci
          echo "$OCI_CLI_KEY_CONTENT" > ~/.oci/private_key.pem
          chmod 600 ~/.oci/private_key.pem

          cat > ~/.oci/config <<EOF
          [DEFAULT]
          user=${OCI_CLI_USER}
          fingerprint=${OCI_CLI_FINGERPRINT}
          key_file=/home/runner/.oci/private_key.pem
          tenancy=${OCI_CLI_TENANCY}
          region=${OCI_CLI_REGION}
          EOF

      - name: Test Authentication
        run: |
          echo "Testing OCI access using 'oci os ns get'..."
          oci os ns get --query "data" --raw-output
          echo "Success! OCI authentication works."
