name: Create TFC Project and Workspaces

on:
  workflow_dispatch:
  push:
    branches:
      - feature/create-tfc-project-and-workspace

jobs:
  create-resources:
    runs-on: arc-runner-set

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create Terraform Cloud Project
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: ${{ secrets.TFC_ORG }}
          PROJECT_NAME: sample-project-api
        run: |
          echo "🚀 Creating Terraform Cloud Project: $PROJECT_NAME"

          response=$(curl -s --request POST \
            --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/projects" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data "{
              \"data\": {
                \"type\": \"projects\",
                \"attributes\": {
                  \"name\": \"$PROJECT_NAME\"
                }
              }
            }")

          echo "$response" | jq .

          project_id=$(echo "$response" | jq -r '.data.id')

          if [[ "$project_id" == "null" ]]; then
            echo "❌ Failed to create project."
            exit 1
          else
            echo "✅ Project created with ID: $project_id"
          fi
