terraform init
terraform plan -var="tfe_token=your_token" -var="organization=your_org" -var="workspace_id=your_workspace_id"
terraform apply -auto-approve -var="tfe_token=..." -var="organization=..." -var="workspace_id=..."
