 Inputs for Creation Workflow
system
System identifier
Example: enterprise
Required: ✅

app
Application name
Example: demo
Required: ✅

workspace_count
Number of workspaces to create
Example: 3
Required: ✅

workspace_usage
(Optional) Comma-separated usage labels for each workspace
Example: david,shyam,s3
Required: ❌

team_name
TFC team name to create/assign
Example: devops-poc
Required: ✅

sso_id
Azure AD SSO group ID
Example: MGSITSOCIAdmins
Required: ✅

confirm_reuse
Type YES to reuse existing project if present
Example: YES
Required: ❌
