6s
Run echo "Sanitizing input..."
  
Sanitizing input...
Looking up team ID for 'team-demo-test-5'...
All team names returned by API:
architecture
container
core-cloud
corporate-systems
database
datacom
data-protection
dbin-benigtr-dev
dbin-benigtr-sre
dcdp-col-dev
dcdp-col-sre
devops
digital-transformation-office
dnex-cia-dev
dnex-cia-sre
observability
owners
ppop-autobr-dev
ppop-autobr-sre
pprp-prpptl-dev
pprp-prpptl-sre
pse
security
sso
storage
team-demo-test
team-demo-test-1
team-demo-test-2
team-demo-test-5
telecom
unix
Deleting team with ID: team-GhfxTXDAJdDYfCXd
Team 'team-demo-test-5' deleted successfully.
