name: delete-team

on:
  workflow_dispatch:
    inputs:
      TEAM_NAME:
        description: 'Team name to delete'
        required: true

jobs:
  delete:
    runs-on: arc-runner-set
    steps:
      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Delete team by name
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: ${{ secrets.TFC_ORG }}
          TEAM_NAME: ${{ github.event.inputs.TEAM_NAME }}
        run: |
          echo "Sanitizing input..."
          TEAM_NAME=$(echo "$TEAM_NAME" | xargs)

          echo "Looking up team ID for '$TEAM_NAME'..."
          TEAM_ID=""
          PAGE_NUMBER=1

          while true; do
            response=$(curl -s --request GET \
              --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/teams?page[number]=$PAGE_NUMBER" \
              --header "Authorization: Bearer $TFC_TOKEN" \
              --header "Content-Type: application/vnd.api+json")

            echo "Page $PAGE_NUMBER - Team names:"
            echo "$response" | jq -r '.data[].attributes.name'

            TEAM_ID=$(echo "$response" | jq -r --arg tname "$TEAM_NAME" '.data[] | select(.attributes.name == $tname) | .id')

            if [[ -n "$TEAM_ID" && "$TEAM_ID" != "null" ]]; then
              echo "Found team ID: $TEAM_ID"
              break
            fi

            HAS_NEXT=$(echo "$response" | jq -r '"\(.meta.pagination.next-page)"')
            if [[ -z "$HAS_NEXT" || "$HAS_NEXT" == "null" ]]; then
              echo "Team '$TEAM_NAME' not found in any page."
              exit 1
            fi
            PAGE_NUMBER=$HAS_NEXT
          done

          echo "Deleting team ID: $TEAM_ID..."
          delete_response=$(curl -s -o /dev/null -w "%{http_code}" --request DELETE \
            --url "https://app.terraform.io/api/v2/teams/$TEAM_ID" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json")

          if [[ "$delete_response" == "204" ]]; then
            echo "Team '$TEAM_NAME' successfully deleted."
          else
            echo "Failed to delete team '$TEAM_NAME'. HTTP status: $delete_response"
            exit 1
          fi
