name: Create OCI Credential in Jenkins

on:
  workflow_dispatch:
  push:
    branches:
      - feature/create-oci-credential-jenkins

jobs:
  create-oci-credential-in-jenkins:
    runs-on: arc-runner-set

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq dnsutils

      - name: Retrieve Vault Secret
        id: retrieve-secret
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        env:
          OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING: "True"
          OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_API_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
        with:
          command: >
            oci secrets secret-bundle get
            --secret-id "${{ secrets.OCI_VAULT_SECRET_OCID }}"
            --query "data.\"secret-bundle-content\".content"
            --raw-output

      - name: Decode and Parse Vault Secret
        env:
          SECRET_CONTENT: ${{ steps.retrieve-secret.outputs.raw_output }}
          OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
        run: |
          DECODED_CONTENT="$SECRET_CONTENT"
          if [ -z "$DECODED_CONTENT" ]; then
            echo "::error::Secret content is empty"
            exit 1
          fi

          TENANCY_ID=$(echo "$DECODED_CONTENT" | grep '^tenancy=' | cut -d'=' -f2)
          USER_ID=$(echo "$DECODED_CONTENT" | grep '^user=' | cut -d'=' -f2 || echo "$OCI_CLI_USER")
          FINGERPRINT=$(echo "$DECODED_CONTENT" | grep '^fingerprint=' | cut -d'=' -f2)
          REGION=$(echo "$DECODED_CONTENT" | grep '^region=' | cut -d'=' -f2)
          PRIVATE_KEY=$(echo "$DECODED_CONTENT" | sed -n '/^private_key=/,/-----END RSA PRIVATE KEY-----/p' | sed 's/^private_key=//')

          echo "::add-mask::$TENANCY_ID"
          echo "::add-mask::$USER_ID"
          echo "::add-mask::$FINGERPRINT"
          echo "::add-mask::$PRIVATE_KEY"

          echo "TENANCY_ID=$TENANCY_ID" >> $GITHUB_ENV
          echo "USER_ID=$USER_ID" >> $GITHUB_ENV
          echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV
          echo "REGION=$REGION" >> $GITHUB_ENV
          echo "PRIVATE_KEY=$PRIVATE_KEY" >> $GITHUB_ENV
          echo "CREDENTIAL_ID=oci-vault-credential-$(date +%s)" >> $GITHUB_ENV

      - name: Get Jenkins CSRF Crumb
        id: crumb
        env:
          JENKINS_URL: ${{ secrets.JENKINS_BASE_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            "$JENKINS_URL/crumbIssuer/api/json")
          
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d':' -f2)
          CRUMB_JSON=$(echo "$RESPONSE" | grep -v "HTTP_STATUS")

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "::error::Failed to fetch CSRF crumb. HTTP $HTTP_STATUS"
            exit 1
          fi

          echo "crumb_field=$(echo "$CRUMB_JSON" | jq -r .crumbRequestField)" >> $GITHUB_OUTPUT
          echo "crumb_value=$(echo "$CRUMB_JSON" | jq -r .crumb)" >> $GITHUB_OUTPUT

      - name: Create OCI Credential in Jenkins Folder
        env:
          JENKINS_URL: ${{ secrets.JENKINS_BASE_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          CREDENTIAL_ID: ${{ env.CREDENTIAL_ID }}
          TENANCY_ID: ${{ env.TENANCY_ID }}
          USER_ID: ${{ env.USER_ID }}
          FINGERPRINT: ${{ env.FINGERPRINT }}
          PRIVATE_KEY: ${{ env.PRIVATE_KEY }}
          REGION: ${{ env.REGION }}
          CRUMB_FIELD: ${{ steps.crumb.outputs.crumb_field }}
          CRUMB_VALUE: ${{ steps.crumb.outputs.crumb_value }}
        run: |
          PRIVATE_KEY_ESCAPED=$(printf '%s' "$PRIVATE_KEY" | sed ':a;N;$!ba;s/\n/\\n/g')

          cat > credential.xml <<EOF
          <com.oracle.cloud.baremetal.jenkins.credentials.BaremetalCloudCredentialsImpl>
            <scope>GLOBAL</scope>
            <id>$CREDENTIAL_ID</id>
            <description>OCI Credential from Vault</description>
            <tenantId>$TENANCY_ID</tenantId>
            <userId>$USER_ID</userId>
            <fingerprint>$FINGERPRINT</fingerprint>
            <privateKey>$PRIVATE_KEY_ESCAPED</privateKey>
            <passPhrase></passPhrase>
            <region>$REGION</region>
            <useInstancePrincipal>false</useInstancePrincipal>
          </com.oracle.cloud.baremetal.jenkins.credentials.BaremetalCloudCredentialsImpl>
          EOF

          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
            -X POST "$JENKINS_URL/view/OCI-POC/job/OCI-CCP/credentials/store/folder/domain/_/createCredentials" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            -H "Content-Type: application/xml" \
            -H "$CRUMB_FIELD: $CRUMB_VALUE" \
            --data @credential.xml)

          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d':' -f2)
          if [[ "$HTTP_STATUS" -ne 200 ]]; then
            echo "::error::Failed to create Jenkins credential. HTTP $HTTP_STATUS"
            exit 1
          fi

          echo "✅ OCI credential created in folder with ID: $CREDENTIAL_ID"
