name: Automate Sentinel Policy Setup

on:
  push:
    branches:
      - main
    paths:
      - 'policy-automation/**'
      - 'sentinel-policies/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: policy-automation

    env:
      TF_VAR_tfe_token: ${{ secrets.TFE_TOKEN }}
      TF_VAR_organization: ${{ secrets.TFC_ORGANIZATION }}
      TF_VAR_workspace_id: ${{ secrets.TFC_WORKSPACE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: true  # Optional: useful for manual inspection

      - name: Terraform Apply
        run: terraform apply -auto-approve
