name: Delete TFC Team

on:
  workflow_dispatch:
    inputs:
      team_id:
        description: 'Terraform Cloud Team ID (e.g. team-abc123)'
        required: true
        type: string

jobs:
  delete-team:
    runs-on: arc-runner-set
    steps:
      - name: Delete TFC Team
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TEAM_ID: ${{ inputs.team_id }}
        run: |
          echo "🗑️ Deleting team with ID: $TEAM_ID"
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            --request DELETE \
            --url "https://app.terraform.io/api/v2/teams/$TEAM_ID" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json")

          if [[ "$response" -eq 204 ]]; then
            echo "✅ Successfully deleted team $TEAM_ID"
          else
            echo "❌ Failed to delete team $TEAM_ID. HTTP status: $response"
            exit 1
          fi
