Response from team list (truncated):
20
All team names returned by API:
architecture
container
core-cloud
corporate-systems
database
datacom
data-protection
dbin-benigtr-dev
dbin-benigtr-sre
dcdp-col-dev
dcdp-col-sre
devops
digital-transformation-office
dnex-cia-dev
dnex-cia-sre
observability
owners
ppop-autobr-dev
ppop-autobr-sre
pprp-prpptl-dev
Team names with IDs:
architecture => team-eL4PFY9GVE1MJL2g
container => team-kApSD3Wuy1ExdNv8
core-cloud => team-N8weLwSP2vAsnWtF
corporate-systems => team-KK4VwTzabeQsCacf
database => team-28R6N2QdEy5jo6Fz
datacom => team-gvm2DwurTkcbJNco
data-protection => team-Q2UVMoaZrMXLrTVj
dbin-benigtr-dev => team-9YvikQzHgkPrXDj8
dbin-benigtr-sre => team-HGzdSDVce5abWEV8
dcdp-col-dev => team-U9DQouu6znxYfx3p
dcdp-col-sre => team-J5Wd4nqz35f66JV1
devops => team-8NobY9GJwZub6iWx
digital-transformation-office => team-3NsbeW86SK2ds8dN
dnex-cia-dev => team-5667H6fUUmRr3KaR
dnex-cia-sre => team-V6zrK38SVwoH2HAi
observability => team-mv998m9YCg9WAfS5
owners => team-wY5TbphTs83AKxfC
ppop-autobr-dev => team-bfCJiYvAuNPLAVwt
ppop-autobr-sre => team-L2vrXJC6DBUecEFw
pprp-prpptl-dev => team-AmV67gpJaDJRFbAK
Team 'team-demo-test-5' not found.
Error: Process completed with exit code 1.
