name: Create TFC Project and Workspaces

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Enter the Project Name'
        required: true
        type: string
      workspaces:
        description: 'Enter comma-separated workspace names (e.g., dev,qa,prod)'
        required: true
        type: string

jobs:
  create-resources:
    runs-on: arc-runner-set

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create Project and Workspaces
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: ${{ secrets.TFC_ORG }}
          PROJECT_NAME: ${{ inputs.project_name }}
          WORKSPACES: ${{ inputs.workspaces }}
        run: |
          echo "🔍 Checking if project '$PROJECT_NAME' already exists..."

          existing_project_id=$(curl -s --request GET \
            --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/projects" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" | jq -r \
            --arg pname "$PROJECT_NAME" '.data[] | select(.attributes.name == $pname) | .id')

          if [[ -n "$existing_project_id" ]]; then
            echo "⚠️ Project '$PROJECT_NAME' already exists with ID: $existing_project_id"
            exit 0
          fi

          echo "🚀 Creating Terraform Cloud Project: $PROJECT_NAME"

          project_response=$(curl -s --request POST \
            --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/projects" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data "{
              \"data\": {
                \"type\": \"projects\",
                \"attributes\": {
                  \"name\": \"$PROJECT_NAME\"
                }
              }
            }")

          echo "$project_response" | jq .

          project_id=$(echo "$project_response" | jq -r '.data.id')

          if [[ "$project_id" == "null" ]]; then
            echo "❌ Project creation failed."
            exit 1
          fi

          echo "✅ Project created with ID: $project_id"

          IFS=',' read -ra workspace_names <<< "$WORKSPACES"

          for workspace in "${workspace_names[@]}"; do
            echo "🔧 Creating workspace: $workspace"

            workspace_response=$(curl -s --request POST \
              --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/workspaces" \
              --header "Authorization: Bearer $TFC_TOKEN" \
              --header "Content-Type: application/vnd.api+json" \
              --data "{
                \"data\": {
                  \"type\": \"workspaces\",
                  \"attributes\": {
                    \"name\": \"$workspace\"
                  },
                  \"relationships\": {
                    \"project\": {
                      \"data\": {
                        \"id\": \"$project_id\",
                        \"type\": \"projects\"
                      }
                    }
                  }
                }
              }")

            echo "$workspace_response" | jq .

            workspace_id=$(echo "$workspace_response" | jq -r '.data.id')

            if [[ "$workspace_id" == "null" ]]; then
              echo "❌ Workspace $workspace creation failed."
            else
              echo "✅ Workspace $workspace created with ID: $workspace_id"
            fi
          done
