This guide explains how to use the GitHub repository for managing Terraform Cloud (TFC) resources, including creating and deleting projects, workspaces, and team access. The repository contains two GitHub Actions workflows to automate these tasks.
Overview
The repository provides two workflows to streamline Terraform Cloud resource management:
Create TFC Project, Workspaces, and Assign Team Access: Creates a TFC project, a specified number of workspaces, and assigns write access to a team.

Delete TFC Project, Workspaces, and Team: Deletes a specified project, its associated workspaces, and optionally a team.

These workflows are designed to ensure consistent naming conventions, reduce manual errors, and enforce safety checks for resource creation and deletion.
Prerequisites
Before using the workflows, ensure the following are set up:
Terraform Cloud Account: You need access to a Terraform Cloud organization with a valid API token.

GitHub Repository Access: Ensure you have permissions to the repository containing the workflows.

GitHub Secrets:
TFC_TOKEN: A Terraform Cloud API token with permissions to manage projects, workspaces, and teams.

TFC_ORG: The name of your Terraform Cloud organization.

