Policy automation:

main.tf: 

terraform {
  required_providers {
    tfe = {
      source  = "hashicorp/tfe"
      version = "~> 0.51.0"
    }
  }
}

provider "tfe" {
  token = var.tfe_token
}

resource "tfe_policy" "encryption_policy" {
  name         = "require-bucket-encryption"
  description  = "Enforces kms_key_id on OCI buckets"
  organization = var.organization
  policy       = file("${path.module}/../sentinel-policies/require-bucket-encryption.sentinel")
}

resource "tfe_policy_set" "oci_encryption_policies" {
  name         = "oci-encryption-policies-poc"
  description  = "POC policy set for OCI bucket encryption"
  organization = var.organization
  kind         = "sentinel"
  policy_ids   = [tfe_policy.encryption_policy.id]
}

resource "tfe_workspace_policy_set" "attach_test_workspace" {
  policy_set_id = tfe_policy_set.oci_encryption_policies.id
  workspace_id  = var.workspace_id
}

------

Variables.tf:

variable "tfe_token" {
  description = "Terraform Cloud API Token"
  type        = string
  sensitive   = true
}

variable "organization" {
  description = "Terraform Cloud organization name"
  type        = string
}

variable "workspace_id" {
  description = "Workspace ID to attach the policy set"
  type        = string
}

---------------

terraform.tfvars:

organization = "cldhorizon"
workspace_id = "ws-PyGLgfHrQc9Udb6i" 
