provider "oci" {
  tenancy_ocid     = "ocid1.tenancy.oc1..example"
  user_ocid        = "ocid1.user.oc1..example"
  fingerprint      = "00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff"
  private_key_path = "~/.oci/oci_api_key.pem"
  region           = "us-ashburn-1"
}

resource "oci_objectstorage_bucket" "non_compliant" {
  compartment_id = "ocid1.compartment.oc1..example"
  name           = "non-compliant-bucket-${random_id.unique.hex}"
  namespace      = "your-namespace"
}

resource "oci_objectstorage_bucket" "compliant" {
  compartment_id = "ocid1.compartment.oc1..example"
  name           = "compliant-bucket-${random_id.unique.hex}"
  namespace      = "your-namespace"
  kms_key_id     = "ocid1.key.oc1..example"
}

resource "random_id" "unique" {
  byte_length = 4
}
