- **`project_name`**  
  _TFC project name to delete_  
  _Example_: `oci-enterprise-demo`  
  _Required_: ✅

- **`team_name`**  
  _(Optional) TFC team name to delete_  
  _Example_: `devops-poc`  
  _Required_: ❌

- **`selected_workspaces`**  
  _(Optional) Comma-separated workspace names to delete only_  
  _Example_: `oci-enterprise-demo-david-poc-001`  
  _Required_: ❌

- **`confirm_delete`**  
  _Type `YES` to confirm deletion_  
  _Example_: `YES`  
  _Required_: ✅
