assign_output=$(curl -s -w "\n%{http_code}" --request POST \
  --url "https://app.terraform.io/api/v2/team-workspaces" \
  --header "Authorization: Bearer $TFC_TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --data "{
    \"data\": {
      \"type\": \"team-workspaces\",
      \"attributes\": {
        \"access\": \"write\"
      },
      \"relationships\": {
        \"workspace\": {
          \"data\": {
            \"id\": \"$ws_id\",
            \"type\": \"workspaces\"
          }
        },
        \"team\": {
          \"data\": {
            \"id\": \"$team_id\",
            \"type\": \"teams\"
          }
        }
      }
    }
  }")

# Split output and status code
assign_status=$(echo "$assign_output" | tail -n1)
assign_body=$(echo "$assign_output" | sed '$d')

if [[ "$assign_status" == "201" ]]; then
  echo "Team write access assigned to $ws_id"
else
  echo "Failed to assign team access to $ws_id. Status: $assign_status"
  echo "$assign_body"
fi
