echo "Assigning team to project with ID: $project_id"

project_assign_response=$(curl -s -w "\n%{http_code}" --request POST \
  --url "https://app.terraform.io/api/v2/team-project-access" \
  --header "Authorization: Bearer $TFC_TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --data "{
    \"data\": {
      \"type\": \"team-project-access\",
      \"attributes\": {
        \"access\": \"write\"
      },
      \"relationships\": {
        \"team\": {
          \"data\": {
            \"type\": \"teams\",
            \"id\": \"$team_id\"
          }
        },
        \"project\": {
          \"data\": {
            \"type\": \"projects\",
            \"id\": \"$project_id\"
          }
        }
      }
    }
  }")

project_status=$(echo "$project_assign_response" | tail -n1)
if [[ "$project_status" -eq 201 ]]; then
  echo "Team successfully assigned to project $project_id"
else
  echo "Failed to assign team to project. Status: $project_status"
  echo "$project_assign_response"
fi
