name: Delete TFC Project and Workspaces

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Enter the Project Name to delete'
        required: true
        type: string
      confirm_delete:
        description: 'Type YES to confirm deletion'
        required: true
        type: string

jobs:
  delete-resources:
    runs-on: arc-runner-set

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Delete Project and Workspaces
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: ${{ secrets.TFC_ORG }}
          PROJECT_NAME: ${{ inputs.project_name }}
          CONFIRM_DELETE: ${{ inputs.confirm_delete }}
        run: |
          if [[ "$CONFIRM_DELETE" != "YES" ]]; then
            echo "Deletion not confirmed. Type YES to confirm."
            exit 1
          fi

          echo "Fetching project ID for '$PROJECT_NAME'..."
          project_id=$(curl -s --request GET \
            --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/projects" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" | jq -r \
            --arg pname "$PROJECT_NAME" '.data[] | select(.attributes.name == $pname) | .id')

          if [[ -z "$project_id" ]]; then
            echo "Project '$PROJECT_NAME' not found."
            exit 1
          fi

          echo "Found project: $project_id"
          echo "Fetching workspaces in project..."

          workspaces=$(curl -s --request GET \
            --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/workspaces" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" | jq -r \
            --arg pid "$project_id" '.data[] | select(.relationships.project.data.id == $pid) | .id')

          for ws_id in $workspaces; do
            echo "Deleting workspace: $ws_id"
            curl -s --request DELETE \
              --url "https://app.terraform.io/api/v2/workspaces/$ws_id" \
              --header "Authorization: Bearer $TFC_TOKEN" \
              --header "Content-Type: application/vnd.api+json"
            echo "Deleted workspace $ws_id"
          done

          echo "All workspaces deleted. Deleting project..."
          curl -s --request DELETE \
            --url "https://app.terraform.io/api/v2/projects/$project_id" \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json"

          echo "Project '$PROJECT_NAME' deleted successfully."
