Constant: (We need to hardcode it, no need to pass it as input)
Environment -> poc
Iteration -> 001
 
Dynamic: (inputs)

System -> user input
Application -> user input
No of workspace -> user input
Team name -> user input
SSO ID -> user input
Usage -> user input (optional) -> Usage means something to differentiate the workspaces. 

Example: 

Project name: oci-dbin-benigt
Workspace name: oci-dbin-benigt-<usage=david>-poc-001

So it will be, oci-dbin-benigt-david-poc-001
more examples:
oci-dbin-benigt-shyam-poc-001
oci-dbin-benigt-akshay-poc-001
oci-dbin-benigt-s3-poc-001
oci-dbin-benigt-vm-poc-001

---------

Then we need to make changes as per the below scenerios:
 
Scenerio 1: when no of workspace is 1 and user enter no usage:
Like: oci-dbin-benigt-poc-001
 
Scenerio 2: when no of workspace is 5 and user enter no usage:
If user do not enter any usage value, we increase the iteration by 1.
Like:
oci-dbin-benigt-poc-001
oci-dbin-benigt-poc-002
oci-dbin-benigt-poc-003
oci-dbin-benigt-poc-004
oci-dbin-benigt-poc-005
 
 
Scenerio 3: when no of workspace is 1 and user enter usage as david:
We can create the workspace
Like:
oci-dbin-benigt-david-poc-001
 
Scenerio 4:Case when no of workspace is 5 and user enter usage for all 5 workspace:
usage will be will change and iterations stays same 001
Like:
oci-dbin-benigt-david-poc-001
oci-dbin-benigt-shyam-poc-001
oci-dbin-benigt-akshay-poc-001
oci-dbin-benigt-s3-poc-001
oci-dbin-benigt-vm-poc-001
