package terraform

deny[msg] {
  resource := input.plan.resource_changes[_]
  resource.type == "oci_objectstorage_bucket"
  resource.change.actions[_] == "create"

  # kms_key_id is either not present at all or explicitly empty
  not resource.change.after.kms_key_id
  msg := sprintf("Bucket '%s' does not have kms_key_id defined", [resource.address])
}

deny[msg] {
  resource := input.plan.resource_changes[_]
  resource.type == "oci_objectstorage_bucket"
  resource.change.actions[_] == "create"
  resource.change.after.kms_key_id == ""
  msg := sprintf("Bucket '%s' has an empty kms_key_id", [resource.address])
}
