- name: Install Terraform manually
  run: |
    curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
    unzip terraform.zip
    chmod +x terraform
    echo "${PWD}" >> $GITHUB_PATH
