**Inputs:**

- `system`  
  System identifier  
  Example: `enterprise`, `ppop`  
  Required: ✅

- `app`  
  Application name  
  Example: `demo`, `autobr`  
  Required: ✅

- `workspace_count`  
  Number of workspaces to create  
  Example: `3`  
  Required: ✅

- `workspace_usage`  
  (Optional) Comma-separated usage labels for each workspace  
  Example: `crp,vault`  
  Required: ❌

- `team_name`  
  TFC team name to create/assign  
  Example: `devops-poc`  
  Required: ✅

- `sso_id`  
  Azure AD SSO group ID  
  Example: `MGSITSOCIAdmins`  
  Required: ✅

- `confirm_reuse`  
  Type `YES` to reuse existing project if present  
  Example: `YES`  
  Required: ❌
