echo "Checking if team '$TEAM_NAME' already exists..."
team_id=$(curl -s --request GET \
  --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/teams" \
  --header "Authorization: Bearer $TFC_TOKEN" \
  --header "Content-Type: application/vnd.api+json" | jq -r \
  --arg tname "$TEAM_NAME" '.data[] | select(.attributes.name == $tname) | .id')

if [[ -n "$team_id" ]]; then
  echo "Team '$TEAM_NAME' already exists with ID: $team_id"
else
  echo "Creating team: $TEAM_NAME"
  team_response=$(curl -s --request POST \
    --url "https://app.terraform.io/api/v2/organizations/$TFC_ORG/teams" \
    --header "Authorization: Bearer $TFC_TOKEN" \
    --header "Content-Type: application/vnd.api+json" \
    --data "{
      \"data\": {
        \"type\": \"teams\",
        \"attributes\": {
          \"name\": \"$TEAM_NAME\",
          \"visibility\": \"organization\",
          \"sso-team-id\": \"$SSO_ID\"
        }
      }
    }")
  team_id=$(echo "$team_response" | jq -r '.data.id')

  if [[ "$team_id" == "null" || -z "$team_id" ]]; then
    echo "Team creation failed."
    echo "$team_response"
    exit 1
  fi
  echo "Team created with ID: $team_id"
fi
