for ws_id in "${WORKSPACE_IDS[@]}"; do
  echo "🔗 Assigning team $TEAM_NAME to workspace ID: $ws_id"
  assign_response=$(curl -s -w "\n%{http_code}" --request POST \
    --url "https://app.terraform.io/api/v2/workspaces/$ws_id/relationships/teams" \
    --header "Authorization: Bearer $TFC_TOKEN" \
    --header "Content-Type: application/vnd.api+json" \
    --data "{
      \"data\": [
        {
          \"id\": \"$team_id\",
          \"type\": \"teams\"
        }
      ]
    }")

  assign_status=$(echo "$assign_response" | tail -n1)
  if [[ "$assign_status" == "200" || "$assign_status" == "201" ]]; then
    echo "Team assigned to workspace $ws_id"
  else
    echo "Failed to assign team to workspace $ws_id"
    echo "$assign_response"
    exit 1
  fi
done
