Run python create_compartments.py \
18Traceback (most recent call last):
19  File "/home/runner/work/oci-resources-automation-001/oci-resources-automation-001/create_compartments.py", line 6, in <module>
20    config = oci.config.from_file()
21  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/oci/config.py", line 106, in from_file
22    if not parser.read(expanded_file_location):
23  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/configparser.py", line 699, in read
24    self._read(fp, filename)
25  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/configparser.py", line 1087, in _read
26    raise MissingSectionHeaderError(fpname, lineno, line)
27configparser.MissingSectionHeaderError: File contains no section headers.
28file: '/home/runner/.oci/config', line: 1
29'***\n'
30Error: Process completed with exit code 1.
